kind: Service
apiVersion: v1
metadata:
  name: frontier
spec:
  type: ClusterIP
  selector:
    app: frontier
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: frontier-ingress
